
services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbschool
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    build:
      context: ./Desafio/Desafio
      dockerfile: Dockerfile
    ports:
      - "7145:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;user=root;password=root;database=dbschool;
    depends_on:
        db:
          condition: service_healthy

  frontend:
    build:
      context: ./my-spa
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend



volumes:
  db_data:
